// ============================================
// BLOG YAZILARI (3 dilli) — yeni yazı eklemek için
// aynı formatta bir kayıt ekleyin.
// ============================================
export const POSTS = [
  {
    slugs: { tr: "orumcek-vinc-nedir", en: "what-is-a-spider-crane", de: "was-ist-ein-minikran" },
    date: "2026-07-28",
    cover: "/slider/slide-1.jpg",
    tr: {
      category: "Ekipman Rehberi",
      title: "Örümcek Vinç Nedir, Nerelerde Kullanılır?",
      excerpt: "Dar kapılardan geçip bina içinde bile çalışabilen örümcek vinçler, klasik vinçlerin giremediği her yerde devreye girer.",
      content: [
        { h: "Kompakt gövde, büyük güç" },
        { p: "Örümcek vinçler (spider crane), paletli yürüyüş sistemi ve açılır destek ayakları sayesinde standart bir kapıdan geçebilecek kadar dar, ancak tonlarca yükü kaldırabilecek kadar güçlü makinelerdir. Kapalı alışveriş merkezleri, fabrika içleri, çatı altları ve şehir merkezindeki dar sokaklar en tipik kullanım alanlarıdır." },
        { h: "Nerelerde tercih edilir?" },
        { p: "Cam cephe montajı, çelik konstrüksiyon, heykel ve dekorasyon yerleştirme, asansör motoru değişimi gibi hassas kaldırma gerektiren işlerde örümcek vinç çoğu zaman tek çözümdür. Elektrikli modelleri kapalı alanlarda sıfır emisyonla çalışır." },
        { p: "Filomuzdaki örümcek vinçler farklı tonaj ve bom uzunluklarıyla her projeye uyarlanabilir. Hangi modelin işinize uygun olduğundan emin değilseniz WhatsApp'tan ulaşın, ücretsiz keşifle doğru ekipmanı belirleyelim." },
      ],
    },
    en: {
      category: "Equipment Guide",
      title: "What Is a Spider Crane and Where Is It Used?",
      excerpt: "Spider cranes fit through standard doorways and even work indoors — stepping in wherever classic cranes cannot reach.",
      content: [
        { h: "Compact body, serious power" },
        { p: "Thanks to their crawler tracks and folding outriggers, spider cranes are narrow enough to pass through a standard door yet strong enough to lift several tons. Shopping malls, factory floors, roof spaces and narrow city streets are their typical playground." },
        { h: "Where are they preferred?" },
        { p: "Glass facade installation, steel construction, sculpture placement and elevator motor replacement often make a spider crane the only viable option. Electric models work indoors with zero emissions." },
        { p: "The spider cranes in our fleet come in various tonnages and boom lengths. Not sure which model fits your job? Reach us on WhatsApp for a free survey." },
      ],
    },
    de: {
      category: "Geräte-Ratgeber",
      title: "Was ist ein Minikran und wo wird er eingesetzt?",
      excerpt: "Minikrane passen durch normale Türen und arbeiten sogar in Gebäuden — überall dort, wo klassische Krane nicht hinkommen.",
      content: [
        { h: "Kompakter Körper, große Kraft" },
        { p: "Dank Raupenfahrwerk und klappbaren Abstützungen sind Minikrane schmal genug für eine Standardtür und stark genug für mehrere Tonnen Last. Einkaufszentren, Fabrikhallen, Dachräume und enge Altstadtgassen sind ihr typisches Einsatzgebiet." },
        { h: "Wo werden sie bevorzugt?" },
        { p: "Bei Glasfassaden-Montage, Stahlbau, Skulpturen-Platzierung und Aufzugsmotor-Wechsel ist der Minikran oft die einzige Lösung. Elektrische Modelle arbeiten emissionsfrei in Innenräumen." },
        { p: "Unsere Minikrane gibt es in verschiedenen Tonnagen und Auslegerlängen. Unsicher, welches Modell passt? Schreiben Sie uns per WhatsApp für eine kostenlose Besichtigung." },
      ],
    },
  },
  {
    slugs: { tr: "makasli-platform-kiralama-rehberi", en: "scissor-lift-rental-guide", de: "scherenbuehne-mieten-ratgeber" },
    date: "2026-07-15",
    cover: "/slider/slide-5.jpg",
    tr: {
      category: "Kiralama",
      title: "Makaslı Platform Kiralarken Nelere Dikkat Etmeli?",
      excerpt: "Akülü mü dizel mi? Kaç metre çalışma yüksekliği? Doğru makaslı platformu seçmek için bilmeniz gerekenler.",
      content: [
        { h: "Akülü mü, dizel mi?" },
        { p: "Kapalı ve zemini düzgün alanlarda (AVM, depo, fabrika) akülü makaslı platformlar sessiz ve emisyonsuz çalışır. Açık arazide, bozuk zeminde ve yüksek kapasite gereken işlerde dizel modeller tercih edilir." },
        { h: "Çalışma yüksekliğini doğru hesaplayın" },
        { p: "Platform seçerken ulaşmak istediğiniz nokta değil, çalışma yüksekliği esas alınır: platform taban yüksekliğine yaklaşık 2 metre insan erişimi eklenir. Kiralamadan önce kapı ve asansör ölçülerini, zemin kapasitesini mutlaka paylaşın — ekibimiz keşifte tüm detayları sizinle netleştirir." },
      ],
    },
    en: {
      category: "Rental",
      title: "What to Consider When Renting a Scissor Lift",
      excerpt: "Electric or diesel? How many meters of working height? Everything you need to pick the right scissor lift.",
      content: [
        { h: "Electric or diesel?" },
        { p: "On smooth indoor floors (malls, warehouses, factories) electric scissor lifts run silently with zero emissions. For outdoor terrain, rough ground and higher capacities, diesel models are the way to go." },
        { h: "Calculate working height correctly" },
        { p: "What matters is working height, not just the point you want to reach: add roughly 2 meters of human reach to the platform height. Before renting, share door and elevator dimensions and floor capacity — our team clarifies every detail during the free survey." },
      ],
    },
    de: {
      category: "Vermietung",
      title: "Worauf Sie beim Mieten einer Scherenbühne achten sollten",
      excerpt: "Elektrisch oder Diesel? Wie viel Arbeitshöhe? Alles Wichtige zur Wahl der richtigen Scherenbühne.",
      content: [
        { h: "Elektrisch oder Diesel?" },
        { p: "Auf glatten Innenböden (Einkaufszentren, Lager, Fabriken) arbeiten Elektro-Scherenbühnen leise und emissionsfrei. Im Außenbereich, auf unebenem Gelände und bei höheren Kapazitäten sind Dieselmodelle die richtige Wahl." },
        { h: "Arbeitshöhe richtig berechnen" },
        { p: "Entscheidend ist die Arbeitshöhe, nicht nur der Zielpunkt: Zur Plattformhöhe kommen etwa 2 Meter Greifhöhe hinzu. Teilen Sie vor der Miete Tür- und Aufzugsmaße sowie Bodenbelastung mit — unser Team klärt alle Details bei der kostenlosen Besichtigung." },
      ],
    },
  },
  {
    slugs: { tr: "vinc-operasyonlarinda-is-guvenligi", en: "crane-safety-golden-rules", de: "kransicherheit-goldene-regeln" },
    date: "2026-06-30",
    cover: "/slider/slide-4.jpg",
    tr: {
      category: "İş Güvenliği",
      title: "Vinç Operasyonlarında İş Güvenliği: 7 Altın Kural",
      excerpt: "Vinç işinde ikinci şansa yer yoktur. Her operasyonda uyguladığımız temel güvenlik prensiplerini derledik.",
      content: [
        { p: "Vinç kaynaklı kazaların büyük bölümü planlama eksikliğinden doğar. Her operasyonumuzda istisnasız uyguladığımız kuralları paylaşıyoruz:" },
        { p: "1) Operasyon öncesi saha keşfi ve risk analizi yapılır. 2) Zemin taşıma kapasitesi doğrulanır. 3) Yük tablosunun dışına asla çıkılmaz. 4) Sapan ve aparatlar her kullanımdan önce kontrol edilir. 5) Rüzgar limitleri aşıldığında operasyon durdurulur. 6) Yük altında kimse bulundurulmaz. 7) Operatör ile işaretçi arasında kesintisiz iletişim sağlanır." },
        { p: "Tüm operatörlerimiz sertifikalıdır ve operasyonlarımız sigorta kapsamındadır. Güvenlikten taviz vermeyen bir çözüm ortağı arıyorsanız doğru yerdesiniz." },
      ],
    },
    en: {
      category: "Work Safety",
      title: "Crane Safety: 7 Golden Rules We Never Break",
      excerpt: "In crane work there is no room for second chances. Here are the core safety principles we apply on every job.",
      content: [
        { p: "Most crane accidents stem from poor planning. These are the rules we apply on every single operation without exception:" },
        { p: "1) Site survey and risk analysis before the job. 2) Ground bearing capacity verified. 3) Never exceed the load chart. 4) Slings and rigging inspected before each use. 5) Operation stops when wind limits are exceeded. 6) No one under the load, ever. 7) Continuous communication between operator and signaller." },
        { p: "All our operators are certified and every operation is insured. If you are looking for a partner that never compromises on safety, you are in the right place." },
      ],
    },
    de: {
      category: "Arbeitssicherheit",
      title: "Kransicherheit: 7 goldene Regeln",
      excerpt: "Bei Kranarbeit gibt es keine zweite Chance. Diese Sicherheitsprinzipien gelten bei jedem unserer Einsätze.",
      content: [
        { p: "Die meisten Kranunfälle entstehen durch mangelhafte Planung. Diese Regeln wenden wir ausnahmslos bei jedem Einsatz an:" },
        { p: "1) Ortsbegehung und Risikoanalyse vor dem Einsatz. 2) Bodentragfähigkeit wird geprüft. 3) Die Lasttabelle wird nie überschritten. 4) Anschlagmittel werden vor jedem Einsatz kontrolliert. 5) Bei Überschreiten der Windlimits wird gestoppt. 6) Niemand hält sich unter der Last auf. 7) Ständige Kommunikation zwischen Bediener und Einweiser." },
        { p: "Alle unsere Bediener sind zertifiziert und jeder Einsatz ist versichert. Wenn Sie einen Partner suchen, der bei Sicherheit keine Kompromisse macht, sind Sie hier richtig." },
      ],
    },
  },
  {
    slugs: { tr: "arac-ustu-platform-avantajlari", en: "truck-mounted-platform-advantages", de: "lkw-arbeitsbuehnen-vorteile" },
    date: "2026-06-10",
    cover: "/slider/slide-3.jpg",
    tr: {
      category: "Ekipman Rehberi",
      title: "Araç Üstü Platformların Avantajları",
      excerpt: "Şehir içi işlerde hız her şeydir. Araç üstü platformlar kurulum gerektirmeden dakikalar içinde çalışmaya başlar.",
      content: [
        { p: "Araç üstü platformlar kendi motoruyla iş noktasına ulaşır ve destek ayaklarını açarak dakikalar içinde çalışmaya hazır hale gelir. Nakliye maliyeti gerektirmemesi ve gün içinde birden fazla noktada çalışabilmesi en büyük avantajıdır." },
        { h: "Tipik kullanım alanları" },
        { p: "Sokak aydınlatması, tabela montajı, cephe temizliği, ağaç budama ve çatı kontrolleri araç üstü platformların günlük işleridir. 14 metreden 40+ metreye kadar erişim seçenekleri sunuyoruz. Rezervasyon için WhatsApp hattımız 7/24 açık." },
      ],
    },
    en: {
      category: "Equipment Guide",
      title: "The Advantages of Truck-Mounted Platforms",
      excerpt: "In urban jobs speed is everything. Truck-mounted platforms drive to the site and start working within minutes.",
      content: [
        { p: "Truck-mounted platforms drive themselves to the job site and are ready to work within minutes once the outriggers are set. No transport cost and the ability to cover multiple locations in one day are their biggest advantages." },
        { h: "Typical use cases" },
        { p: "Street lighting maintenance, signage installation, facade cleaning, tree trimming and roof inspections are everyday jobs for truck-mounted platforms. We offer reach options from 14 to 40+ meters. Our WhatsApp line is open 24/7 for reservations." },
      ],
    },
    de: {
      category: "Geräte-Ratgeber",
      title: "Die Vorteile von LKW-Arbeitsbühnen",
      excerpt: "Im Stadtgebiet zählt Geschwindigkeit. LKW-Arbeitsbühnen fahren zum Einsatzort und sind in Minuten arbeitsbereit.",
      content: [
        { p: "LKW-Arbeitsbühnen fahren selbst zum Einsatzort und sind nach dem Abstützen in wenigen Minuten einsatzbereit. Keine Transportkosten und mehrere Einsatzorte an einem Tag — das sind ihre größten Vorteile." },
        { h: "Typische Einsatzgebiete" },
        { p: "Straßenbeleuchtung, Schildermontage, Fassadenreinigung, Baumschnitt und Dachkontrollen gehören zum Alltag der LKW-Bühnen. Wir bieten Reichweiten von 14 bis über 40 Meter. Unsere WhatsApp-Linie ist rund um die Uhr für Reservierungen offen." },
      ],
    },
  },

  {
    slugs: { tr: "makasli-platform-icin-belge-gerekir-mi", en: "do-you-need-a-license-for-scissor-lifts", de: "braucht-man-einen-schein-fuer-scherenbuehnen" },
    date: "2026-05-25",
    cover: "/gallery/g7.jpg",
    tr: { category: "Kiralama", title: "Makaslı Platform Kullanmak İçin Belge Gerekir mi?",
      excerpt: "Operatörsüz kiralanan platformlarda hangi belgeler zorunlu? IPAF ve MYK belgeleri hakkında bilmeniz gerekenler.",
      content: [
        { p: "Makaslı platformlar operatörsüz kiralanabilen makine grubuna girer; ancak bu, herkesin kullanabileceği anlamına gelmez. Mevzuata göre platformu kullanacak personelin MYK mesleki yeterlilik belgesi veya IPAF eğitim sertifikasına sahip olması gerekir." },
        { h: "Belgeniz yoksa ne olur?" },
        { p: "Belgesiz kullanım hem iş güvenliği riski hem de denetimlerde idari yaptırım doğurur. Ekibinizde belgeli personel yoksa iki seçeneğiniz var: operatörlü kiralama yapmak ya da teslimatta verdiğimiz kullanım eğitiminden yararlanmak. Her iki konuda da kiralamadan önce bize danışmanız yeterli." },
      ] },
    en: { category: "Rental", title: "Do You Need a License to Operate a Scissor Lift?",
      excerpt: "Which certificates are mandatory for self-operated platforms? What you need to know about IPAF and MYK.",
      content: [
        { p: "Scissor lifts belong to the self-operated rental class — but that does not mean anyone can drive one. Regulations require the operator to hold an MYK vocational certificate or IPAF training card." },
        { h: "What if you have no certificate?" },
        { p: "Uncertified use creates both a safety risk and administrative penalties in inspections. If your team has no certified staff, you have two options: rent with an operator, or use the hands-on training we provide at delivery. Just ask us before renting." },
      ] },
    de: { category: "Vermietung", title: "Braucht man einen Schein für Scherenbühnen?",
      excerpt: "Welche Nachweise sind bei selbstbedienten Bühnen Pflicht? Wissenswertes zu IPAF- und MYK-Zertifikaten.",
      content: [
        { p: "Scherenbühnen gehören zur selbstbedienten Mietklasse — das heißt aber nicht, dass jeder sie fahren darf. Vorschriften verlangen ein MYK-Berufszertifikat oder eine IPAF-Schulungskarte." },
        { h: "Und ohne Zertifikat?" },
        { p: "Unzertifizierte Nutzung bedeutet Sicherheitsrisiko und Bußgelder bei Kontrollen. Ohne zertifiziertes Personal gibt es zwei Wege: Miete mit Bediener oder unsere Einweisung bei der Lieferung. Fragen Sie uns einfach vor der Miete." },
      ] },
  },
  {
    slugs: { tr: "manlift-kiralama-fiyatini-etkileyen-faktorler", en: "what-affects-manlift-rental-prices", de: "was-beeinflusst-buehnen-mietpreise" },
    date: "2026-05-12",
    cover: "/gallery/g6.jpg",
    tr: { category: "Kiralama", title: "Manlift Kiralama Fiyatını Etkileyen 5 Faktör",
      excerpt: "Aynı yükseklikteki iki platform neden farklı fiyata kiralanır? Fiyatı belirleyen gerçek etkenler.",
      content: [
        { p: "Kiralama fiyatını belirleyen ilk etken çalışma yüksekliğidir; yükseklik arttıkça bedel artar. İkinci etken makine teknolojisidir: dizel ve 4x4 modeller, aynı yükseklikteki akülü modellere göre daha yüksek maliyetlidir." },
        { p: "Üçüncü etken kiralama süresidir — aylık kiralamalarda günlük birim fiyat ciddi oranda düşer. Dördüncüsü operatör talebi, beşincisi ise nakliye mesafesidir. Net fiyat için konum ve iş detayını iletmeniz yeterli; keşif ve fiyatlandırma ücretsizdir." },
      ] },
    en: { category: "Rental", title: "5 Factors That Determine Manlift Rental Prices",
      excerpt: "Why do two platforms of the same height rent at different prices? The real drivers behind the cost.",
      content: [
        { p: "The first driver is working height — the higher the platform, the higher the fee. The second is technology: diesel and 4x4 models cost more than battery models of the same height." },
        { p: "The third is rental duration — monthly rates drop the daily unit price significantly. Fourth comes operator demand and fifth transport distance. Share your location and job details for an exact figure; survey and pricing are free." },
      ] },
    de: { category: "Vermietung", title: "5 Faktoren, die den Bühnen-Mietpreis bestimmen",
      excerpt: "Warum kosten zwei gleich hohe Bühnen unterschiedlich viel? Die echten Preistreiber im Überblick.",
      content: [
        { p: "Erster Faktor ist die Arbeitshöhe — je höher, desto teurer. Zweiter Faktor ist die Technik: Diesel- und 4x4-Modelle kosten mehr als gleich hohe Elektromodelle." },
        { p: "Dritter Faktor ist die Mietdauer — Monatsmieten senken den Tagespreis deutlich. Viertens zählt der Bedienerbedarf, fünftens die Transportstrecke. Für einen Festpreis genügen Standort und Auftragsdetails; Besichtigung und Kalkulation sind kostenlos." },
      ] },
  },
  {
    slugs: { tr: "eklemli-mi-makasli-mi", en: "boom-lift-or-scissor-lift", de: "gelenkbuehne-oder-scherenbuehne" },
    date: "2026-04-28",
    cover: "/gallery/g5.jpg",
    tr: { category: "Ekipman Rehberi", title: "Eklemli Platform mu, Makaslı Platform mu?",
      excerpt: "İki platform tipi arasındaki temel fark ve hangi işte hangisini seçmeniz gerektiği.",
      content: [
        { p: "Makaslı platformlar yalnızca dikey yükselir; geniş sepetiyle birden fazla kişinin malzemeyle birlikte çalışmasına uygundur. Cephe kaplama, tavan tesisatı ve raf montajı gibi doğrudan altına yaklaşabildiğiniz işlerin makinesidir." },
        { p: "Eklemli platformlar ise kollarını kırarak engellerin üzerinden uzanır: bir makinenin, borunun veya çatının ötesindeki noktaya erişmeniz gerekiyorsa tek doğru cevap eklemlidir. Karar kuralı basittir: çalışacağınız noktanın tam altına gelebiliyorsanız makaslı, gelemiyorsanız eklemli." },
      ] },
    en: { category: "Equipment Guide", title: "Boom Lift or Scissor Lift?",
      excerpt: "The key difference between the two platform types and which one to pick for which job.",
      content: [
        { p: "Scissor lifts rise strictly vertically; their large basket lets several workers operate with materials. They are the machine for facade cladding, ceiling installations and racking — any job you can stand directly beneath." },
        { p: "Boom lifts articulate over obstacles: if you must reach beyond a machine, pipe or roof edge, a boom is the only right answer. The rule is simple: if you can position directly under the work point, take a scissor; if not, take a boom." },
      ] },
    de: { category: "Geräte-Ratgeber", title: "Gelenkbühne oder Scherenbühne?",
      excerpt: "Der zentrale Unterschied beider Bühnentypen — und welche für welchen Einsatz die richtige ist.",
      content: [
        { p: "Scherenbühnen heben rein vertikal; der große Korb erlaubt mehreren Personen das Arbeiten mit Material. Ideal für Fassaden, Deckeninstallationen und Regalmontage — überall, wo man direkt darunter stehen kann." },
        { p: "Gelenkbühnen greifen über Hindernisse hinweg: Muss ein Punkt hinter einer Maschine, einem Rohr oder einer Dachkante erreicht werden, ist die Gelenkbühne die einzige richtige Wahl. Die Regel ist einfach: direkt darunter positionierbar → Schere; sonst → Gelenk." },
      ] },
  },
  {
    slugs: { tr: "vincle-esya-tasima-rehberi", en: "furniture-hoisting-by-crane-guide", de: "moebellift-per-kran-ratgeber" },
    date: "2026-04-15",
    cover: "/gallery/g10.jpg",
    tr: { category: "Kiralama", title: "Vinçle Eşya Taşıma: Dar Merdivenlere Kesin Çözüm",
      excerpt: "Asansöre sığmayan koltuk, merdivene girmeyen dolap... Vinçle eşya alma-verme nasıl işler?",
      content: [
        { p: "Yüksek katlı taşınmalarda en büyük sorun, büyük mobilya ve beyaz eşyanın merdiven ve asansöre sığmamasıdır. Vinçle eşya taşıma bu sorunu kökten çözer: eşyalar balkon veya pencereden, özel sapanlarla güvenle indirilip kaldırılır." },
        { h: "Süreç nasıl işler?" },
        { p: "Bize kat bilgisi, cephe fotoğrafı ve yaklaşık eşya listesini iletirsiniz; uygun tonajda aracı yönlendiririz. Ortalama bir daire taşımasında vinç operasyonu 1-2 saat sürer. Tüm operasyon eşya sigortası kapsamındadır ve fiyat işin başında sabitlenir." },
      ] },
    en: { category: "Rental", title: "Furniture Hoisting by Crane: The Fix for Narrow Stairs",
      excerpt: "A sofa that won't fit the elevator, a wardrobe that won't turn the stairwell — how crane hoisting works.",
      content: [
        { p: "The biggest headache in high-floor moves is furniture that fits neither stairs nor elevator. Crane hoisting solves it at the root: items are lifted safely through the balcony or window with special slings." },
        { h: "How does it work?" },
        { p: "Send us the floor number, a facade photo and a rough item list; we dispatch the right tonnage vehicle. A typical apartment move takes 1-2 hours of crane time. The whole operation is insured and the price is fixed upfront." },
      ] },
    de: { category: "Vermietung", title: "Möbellift per Kran: Die Lösung für enge Treppen",
      excerpt: "Das Sofa passt nicht in den Aufzug, der Schrank nicht ums Treppeneck — so funktioniert das Heben per Kran.",
      content: [
        { p: "Das größte Problem bei Umzügen in obere Etagen: Möbel, die weder in Treppe noch Aufzug passen. Der Kran löst das an der Wurzel — über Balkon oder Fenster werden die Stücke mit Spezialgurten sicher gehoben." },
        { h: "So läuft es ab" },
        { p: "Sie senden Etage, Fassadenfoto und grobe Möbelliste; wir schicken das passende Fahrzeug. Ein typischer Wohnungsumzug braucht 1-2 Stunden Kranzeit. Der Einsatz ist versichert, der Preis vorab fix." },
      ] },
  },
  {
    slugs: { tr: "forklift-kiralarken-dikkat-edilecekler", en: "what-to-check-before-renting-a-forklift", de: "worauf-beim-stapler-mieten-achten" },
    date: "2026-04-02",
    cover: "/gallery/g2.jpg",
    tr: { category: "Ekipman Rehberi", title: "Forklift Kiralarken Nelere Dikkat Etmeli?",
      excerpt: "Dizel mi akülü mü, kaç ton, hangi asansör yüksekliği? Doğru forklifti seçmenin kısa rehberi.",
      content: [
        { p: "İlk soru kapasitedir: taşıyacağınız en ağır paletin ağırlığına yüzde 20 pay ekleyin. İkinci soru çalışma ortamıdır — kapalı depo ve gıda tesislerinde akülü, açık saha ve rampalı alanlarda dizel forklift doğru seçimdir." },
        { p: "Üçüncü kritik detay asansör (mast) yüksekliğidir: raf sisteminizin en üst kirişine forkliftin çatalı ulaşabilmelidir. Kapı ve koridor ölçülerinizi de paylaşırsanız dönüş yarıçapı uygun modeli birlikte belirleriz." },
      ] },
    en: { category: "Equipment Guide", title: "What to Check Before Renting a Forklift",
      excerpt: "Diesel or electric, how many tons, which mast height? A short guide to choosing the right forklift.",
      content: [
        { p: "The first question is capacity: take your heaviest pallet and add a 20% margin. The second is environment — electric for indoor warehouses and food facilities, diesel for open yards and ramps." },
        { p: "The third critical detail is mast height: the forks must reach the top beam of your racking. Share door and aisle dimensions too, and we will match a model with the right turning radius." },
      ] },
    de: { category: "Geräte-Ratgeber", title: "Worauf Sie beim Stapler-Mieten achten sollten",
      excerpt: "Diesel oder Elektro, wie viele Tonnen, welche Masthöhe? Der kurze Leitfaden zum richtigen Stapler.",
      content: [
        { p: "Erste Frage: die Tragkraft — nehmen Sie Ihre schwerste Palette plus 20 % Reserve. Zweite Frage: die Umgebung — Elektro für Hallen und Lebensmittelbetriebe, Diesel für Freiflächen und Rampen." },
        { p: "Drittes Detail ist die Masthöhe: Die Gabeln müssen den obersten Regalträger erreichen. Teilen Sie auch Tor- und Gangmaße mit — wir wählen ein Modell mit passendem Wenderadius." },
      ] },
  },
  {
    slugs: { tr: "yuksekte-calismada-kisisel-koruyucu-donanim", en: "ppe-for-working-at-height", de: "psa-fuer-arbeiten-in-der-hoehe" },
    date: "2026-03-20",
    cover: "/gallery/g3.jpg",
    tr: { category: "İş Güvenliği", title: "Yüksekte Çalışmada Kişisel Koruyucu Donanım",
      excerpt: "Platform sepetine çıkmadan önce üzerinizde ne olmalı? KKD'nin olmazsa olmazları.",
      content: [
        { p: "Eklemli ve araç üstü platformlarda paraşüt tipi emniyet kemeri ve kısa lanyard zorunludur; kemer sepetteki ankraj noktasına bağlanır. Baret, iş ayakkabısı ve reflektif yelek her platform tipinde standarttır." },
        { p: "Sık yapılan hata, makaslı platformda kemer takmanın gereksiz sanılmasıdır — sepet dışına uzanılan her işte kemer hayat kurtarır. Ekipman tesliminde KKD kontrol listemizi de paylaşıyor, talep halinde donanım temini konusunda yönlendiriyoruz." },
      ] },
    en: { category: "Work Safety", title: "PPE for Working at Height",
      excerpt: "What must you wear before stepping into the basket? The non-negotiables of personal protection.",
      content: [
        { p: "On boom and truck-mounted platforms, a full-body harness with a short lanyard is mandatory, attached to the basket anchor point. Helmet, safety boots and a hi-vis vest are standard on every platform type." },
        { p: "A common mistake is assuming harnesses are unnecessary on scissor lifts — whenever you lean beyond the rail, the harness saves lives. We share our PPE checklist at delivery and can advise on sourcing equipment." },
      ] },
    de: { category: "Arbeitssicherheit", title: "PSA für Arbeiten in der Höhe",
      excerpt: "Was gehört an den Körper, bevor Sie in den Korb steigen? Die Pflichtausstattung im Überblick.",
      content: [
        { p: "Auf Gelenk- und LKW-Bühnen ist ein Auffanggurt mit kurzem Verbindungsmittel Pflicht, eingehängt am Anschlagpunkt des Korbs. Helm, Sicherheitsschuhe und Warnweste sind auf jeder Bühne Standard." },
        { p: "Ein häufiger Irrtum: Auf Scherenbühnen sei kein Gurt nötig — sobald über das Geländer hinausgearbeitet wird, rettet der Gurt Leben. Bei der Lieferung erhalten Sie unsere PSA-Checkliste; gern beraten wir auch zur Beschaffung." },
      ] },
  },
  {
    slugs: { tr: "kis-aylarinda-vinc-ve-platform-operasyonlari", en: "crane-and-platform-operations-in-winter", de: "kran-und-buehnen-einsaetze-im-winter" },
    date: "2026-03-08",
    cover: "/gallery/g4.jpg",
    tr: { category: "İş Güvenliği", title: "Kış Aylarında Vinç ve Platform Operasyonları",
      excerpt: "Rüzgar, yağış ve don... Kış şartlarında operasyonlar nasıl güvenle sürdürülür?",
      content: [
        { p: "Kışın en kritik parametre rüzgardır: platformlar için genel sınır 12,5 m/s'dir ve bu değer aşıldığında operasyon durdurulur. Don ve buzlanma günlerinde destek ayaklarının altına genişletilmiş plakalar konulur, zemin kontrolü iki kez yapılır." },
        { p: "Dizel makinelerimiz kış yakıtı ve akü bakımıyla soğuğa hazırlanır; operatörlerimize kış çalışma prosedürü eğitimi verilir. Kış projelerinizde hava penceresini birlikte planlar, riskli günlerde ücretsiz tarih değişikliği sunarız." },
      ] },
    en: { category: "Work Safety", title: "Crane and Platform Operations in Winter",
      excerpt: "Wind, precipitation and frost — how operations continue safely through winter conditions.",
      content: [
        { p: "The critical winter parameter is wind: the general platform limit is 12.5 m/s, and operations stop above it. On frost days, outrigger pads are enlarged and ground checks are done twice." },
        { p: "Our diesel machines get winter fuel and battery care; operators are trained on cold-weather procedures. For winter projects we plan the weather window together and offer free rescheduling on risky days." },
      ] },
    de: { category: "Arbeitssicherheit", title: "Kran- und Bühneneinsätze im Winter",
      excerpt: "Wind, Niederschlag und Frost — so laufen Einsätze auch im Winter sicher weiter.",
      content: [
        { p: "Der kritische Winterparameter ist der Wind: Die allgemeine Bühnengrenze liegt bei 12,5 m/s — darüber wird gestoppt. An Frosttagen werden die Abstützplatten vergrößert und der Boden doppelt geprüft." },
        { p: "Unsere Dieselmaschinen erhalten Winterkraftstoff und Batteriepflege; die Bediener sind für Kälteprozeduren geschult. Bei Winterprojekten planen wir das Wetterfenster gemeinsam und bieten an Risikotagen kostenlose Terminverschiebung." },
      ] },
  },
  {
    slugs: { tr: "avm-projelerinde-akulu-platform", en: "battery-platforms-for-mall-projects", de: "elektro-buehnen-fuer-einkaufszentren" },
    date: "2026-02-24",
    cover: "/gallery/g8.jpg",
    tr: { category: "Ekipman Rehberi", title: "AVM ve Kapalı Alan Projelerinde Akülü Platform",
      excerpt: "İz bırakmayan lastikler, sıfır emisyon, sessiz çalışma — kapalı alanın altın standardı.",
      content: [
        { p: "AVM, hastane, otel ve gıda tesislerinde çalışmanın üç şartı vardır: sıfır emisyon, düşük gürültü ve zeminde iz bırakmamak. Akülü makaslı ve dikey platformlarımız beyaz dolgu lastikleriyle bu üç şartı da karşılar." },
        { p: "Lityum akülü yeni nesil modellerimiz tek şarjla tam vardiya çalışır ve mesai dışı saatlerde standart prizden şarj edilir. AVM'lerin gece çalışma pencerelerine uygun teslimat ve alım planlaması yapıyoruz." },
      ] },
    en: { category: "Equipment Guide", title: "Battery Platforms for Malls and Indoor Projects",
      excerpt: "Non-marking tyres, zero emissions, silent operation — the gold standard for indoor work.",
      content: [
        { p: "Working in malls, hospitals, hotels and food facilities has three requirements: zero emissions, low noise and non-marking floors. Our battery scissor and vertical platforms meet all three with white non-marking tyres." },
        { p: "New-generation lithium models run a full shift on one charge and recharge from a standard socket after hours. We schedule delivery and pickup around malls' night-work windows." },
      ] },
    de: { category: "Geräte-Ratgeber", title: "Elektro-Bühnen für Einkaufszentren und Innenräume",
      excerpt: "Spurlose Reifen, null Emission, leiser Betrieb — der Goldstandard für Innenprojekte.",
      content: [
        { p: "Arbeiten in Einkaufszentren, Kliniken, Hotels und Lebensmittelbetrieben stellt drei Anforderungen: null Emission, wenig Lärm, keine Spuren am Boden. Unsere Elektro-Scheren- und Vertikalbühnen erfüllen alle drei — mit weißen, nicht färbenden Reifen." },
        { p: "Lithium-Modelle der neuen Generation schaffen eine volle Schicht mit einer Ladung und laden an der normalen Steckdose. Lieferung und Abholung planen wir passend zu den Nachtarbeitsfenstern der Center." },
      ] },
  },
  {
    slugs: { tr: "tabela-montajinda-arac-ustu-platform-secimi", en: "choosing-truck-mounted-platforms-for-signage", de: "lkw-buehnen-fuer-schildermontage-waehlen" },
    date: "2026-02-10",
    cover: "/gallery/g9.jpg",
    tr: { category: "Ekipman Rehberi", title: "Tabela ve Cephe Montajında Araç Üstü Platform Seçimi",
      excerpt: "Yol kenarında hızlı kurulum, yüksek erişim ve trafik yönetimi — doğru aracı seçme rehberi.",
      content: [
        { p: "Tabela montajının doğası gereği işler kısa sürelidir ve gün içinde birden fazla noktaya gidilir. Araç üstü platformlar kurulum gerektirmeden dakikalar içinde çalışmaya başladığı için bu işin standart makinesidir." },
        { p: "Seçimde iki ölçü kritiktir: tabelanın yerden yüksekliği ve kaldırımdan yatay uzaklığı. Yan erişim (outreach) değeri yetersiz kalırsa daha yüksek sınıf araç gerekir. Yol kenarı çalışmalarında koni ve levha düzeni dahil trafik güvenlik planını da ekibimiz üstlenir." },
      ] },
    en: { category: "Equipment Guide", title: "Choosing Truck-Mounted Platforms for Signage Work",
      excerpt: "Fast roadside setup, high reach and traffic management — a guide to picking the right vehicle.",
      content: [
        { p: "Signage jobs are short by nature and cover several spots a day. Truck-mounted platforms start working within minutes without any setup, which makes them the standard machine for this trade." },
        { p: "Two measurements matter: the sign's height above ground and its horizontal distance from the kerb. If the outreach falls short, a higher-class vehicle is needed. On roadside jobs our team also handles the traffic safety plan, cones and signage included." },
      ] },
    de: { category: "Geräte-Ratgeber", title: "LKW-Bühnen für Schilder- und Fassadenmontage",
      excerpt: "Schneller Aufbau am Straßenrand, große Reichweite, Verkehrssicherung — so wählen Sie richtig.",
      content: [
        { p: "Schildermontagen sind naturgemäß kurz und verteilen sich auf mehrere Punkte pro Tag. LKW-Bühnen arbeiten ohne Rüstzeit binnen Minuten — deshalb sind sie die Standardmaschine dieses Gewerks." },
        { p: "Zwei Maße sind entscheidend: die Höhe des Schildes und sein horizontaler Abstand zum Bordstein. Reicht die seitliche Reichweite nicht, braucht es eine größere Klasse. Bei Straßenrandarbeiten übernimmt unser Team auch die Verkehrssicherung samt Kegeln und Beschilderung." },
      ] },
  },
  {
    slugs: { tr: "santiyede-4x4-arazi-tipi-platform-avantajlari", en: "4x4-rough-terrain-platform-advantages", de: "vorteile-von-4x4-gelaendebuehnen" },
    date: "2026-01-28",
    cover: "/gallery/g11.jpg",
    tr: { category: "Ekipman Rehberi", title: "Şantiyede 4x4 Arazi Tipi Platformların Avantajları",
      excerpt: "Çamur, moloz, eğim... Standart platformların kaldığı yerde 4x4 modeller devreye girer.",
      content: [
        { p: "Şantiye zemini nadiren düzgündür: çamur, moloz ve eğim standart platformları çaresiz bırakır. 4x4 arazi tipi makaslı ve eklemli platformlar; iri paletli lastikleri, yüksek şasileri ve otomatik dengeleme ayaklarıyla bu koşullar için tasarlanmıştır." },
        { p: "Yüzde 40'a varan tırmanma kabiliyeti sayesinde rampalı sahalarda ek taşıma gerektirmezler. Dış cephe kaplama, çelik konstrüksiyon ve saha aydınlatma işlerinde zamandan yüzde 30'a varan tasarruf sağladıkları sahada defalarca kanıtlanmıştır." },
      ] },
    en: { category: "Equipment Guide", title: "The Advantages of 4x4 Rough-Terrain Platforms on Site",
      excerpt: "Mud, rubble, slopes — where standard platforms give up, 4x4 models take over.",
      content: [
        { p: "Construction ground is rarely smooth: mud, rubble and slopes defeat standard platforms. 4x4 rough-terrain scissors and booms are built exactly for this, with chunky tyres, high chassis and auto-levelling outriggers." },
        { p: "With gradeability up to 40%, they need no extra transport on ramped sites. On cladding, steelwork and site-lighting jobs they have repeatedly proven time savings of up to 30%." },
      ] },
    de: { category: "Geräte-Ratgeber", title: "Die Vorteile von 4x4-Geländebühnen auf der Baustelle",
      excerpt: "Schlamm, Schutt, Gefälle — wo Standardbühnen aufgeben, übernehmen 4x4-Modelle.",
      content: [
        { p: "Baustellenboden ist selten eben: Schlamm, Schutt und Gefälle überfordern Standardbühnen. 4x4-Geländescheren und -Gelenkbühnen sind genau dafür gebaut — mit groben Reifen, hohem Chassis und selbstnivellierenden Stützen." },
        { p: "Mit bis zu 40 % Steigfähigkeit brauchen sie auf Rampen keinen Zusatztransport. Bei Fassaden-, Stahlbau- und Beleuchtungsarbeiten haben sie Zeiteinsparungen von bis zu 30 % vielfach bewiesen." },
      ] },
  },
];

export const getPost = (lang, slug) => POSTS.find((p) => p.slugs[lang] === slug);
